import { TaskBox } from "task.slint";
export { SlintTask, CurrentTask, Backlog, TaskBox } from "task.slint";

export component HelixFlow inherits Window {
    callback create_task;
    in property <bool> create_enabled: true;
    in-out property <string> task_name: taskbox.task_name;
    taskbox := TaskBox {
        create_task => {
            root.create_task();
        }
        create_enabled: root.create_enabled;
    }
}
