import { TaskBox, Backlog, SlintTask } from "task.slint";
import { HorizontalBox } from "std-widgets.slint";
export { SlintTask, CurrentTask, Backlog, TaskBox } from "task.slint";

export component HelixFlow inherits Window {
    callback create_task;
    callback create_backlog_task <=> this_week_backlog.quick_create_task;
    in property <[SlintTask]> backlog_contents <=> this_week_backlog.tasks;
    in property <bool> create_enabled: true;
    in-out property <string> task_name: taskbox.task_name;
    HorizontalBox {
        this_week_backlog := Backlog {
            backlog_name: "This week";
        }
        taskbox := TaskBox {
            create_task => {
                root.create_task();
            }
            create_enabled: root.create_enabled;
        }
    }
}
