import { Button, LineEdit, VerticalBox } from "std-widgets.slint";
    export component HelixFlow inherits Window {
    callback create_task;
    in property <bool> create_enabled: true;
    in property <string> task_id: "";
    in-out property <string> task_name: task_name_entry.text;
    VerticalBox {
        task_name_entry := LineEdit {
            accessible_label: "Task name";
            placeholder-text: self.accessible_label;
        }

        task_id_display := Text {
            accessible_label: "Task ID";
            text: root.task_id;
            accessible_value: self.text;
        }

        create := Button {
            enabled: root.create_enabled;
            text: "Create";
            clicked() => {
                root.create_task();
            }
        }
    }
}
